src/SimpleAutocomplete.svelte

Sometimes, it is possible to get this exception below on the first autocomplete render. 
Which happens here
https://github.com/pstanoev/simple-svelte-autocomplete/blob/master/src/SimpleAutocomplete.svelte#L461
then https://github.com/pstanoev/simple-svelte-autocomplete/blob/master/src/SimpleAutocomplete.svelte#L519
then https://github.com/pstanoev/simple-svelte-autocomplete/blob/master/src/SimpleAutocomplete.svelte#L365
Because list hasn't been binded to an input element yet. https://github.com/pstanoev/simple-svelte-autocomplete/blob/master/src/SimpleAutocomplete.svelte#L729 
Meaning, this is a race condition since https://github.com/pstanoev/simple-svelte-autocomplete/blob/master/src/SimpleAutocomplete.svelte#L490 is triggering an update, but it is asynchronous, as seen from compiled …

Fix Race condition / NPE when input bind haven't fired yet

---

README.md
src/SimpleAutocomplete.svelte

Fixes #33
This adds a `html5autocomplete` flag, that is disabled by default.

html5autocomplete flag

---

src/SimpleAutocomplete.svelte

Previously dropdown items have been highlighted by two independent
mechanisms
- by keeping the index of highlighted item highlightIndex (for keyboard),
- by css :hover (for mouse).
This caused that often two different items have been highlighted at the
same time - one selected by keyboard, the other by hovering the mouse.
This commit makes the two mechaninsms work seamlessly together so that
at each moment only one item is highlighted. Using mouse and keybord can
be arbitrarily combined.

Improve highlighting of dropdown items

---

README.md
src/App.svelte
src/SimpleAutocomplete.svelte

Related to #42
As discussed in #42, right now a new async request is emitted each time the user press a key. Generally only the final sentence/word typed is useful, but not the intermediary steps. Setting a delay to something like `200` allow to reduce the number of requests emitted.
Javascript is not really my predilection language, so I might do things the wrong way. Do not hesitate to tell me what to fix.

Implemented a delay parameter

---

src/App.svelte
src/SimpleAutocomplete.svelte

This patches simply adds slots to allow users to customize the list items as they want.
This is illustred in `App.svelte` by displaying the color names in the actual color they refer to.

Items customization

---

README.md
src/SimpleAutocomplete.svelte

Fixes #57
In the demo, if you type `réd` for instance, then `red` will be matched.
The inverse is true too, inputs without accents will match items with accents.

Matches items even if diacritics differ

---

README.md
src/App.svelte
src/SimpleAutocomplete.svelte

Fixes #67
- Adds `matchAllKeywords` parameter, that suggest any item with at least one matching keyword.
- Adds `sortByPertinence` parameter, that orders item by number of matching keywords
- ignore keywords order for matching

Reworked keywords matching strategy

---

src/SimpleAutocomplete.svelte

With this patch `Enter` is only catched when the menu is opened. This way one can submit a form by pressing `Enter` when the menu is closed. This is the default behavior for most of the browsers with regular forms.

Allow to send the form by pressing Enter

---

README.md
src/App.svelte
src/SimpleAutocomplete.svelte

This patch is based on #44.
It takes benefit of the bulma `is-loading` CSS class when ajax responses takes time to come. As you can see in the demo, it is a spinner located at the place the arrow is usually.
Fixes #47

Activity indicator

---

src/App.svelte
src/SimpleAutocomplete.svelte

This PR fixes #51 
It allows `searchFunction` to be an [async generator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of#iterating_over_async_generators), thus it makes simple-svelte-autocomplete able to progressively load and display items that can be streamed with a little delay between each.

async generators support

---

README.md
src/App.svelte
src/SimpleAutocomplete.svelte

Fixes #55
I implemented multiple selection:
- enabled when `multiple` is set to `true`
- one click on a list item selects it, a second one unselect it
- selecting a list item resets the input text
- when there is no input text, pressing `backspace` deletes the last tag
Almost all of the code is straightforward, but there is one matter you will probably want to discuss: there is a new `<select>` tag that holds the value(s) in addition to the `<input>` that collects the user input.
Right now its name and id are defined with `selectName` and `selectId`.
Now for someone (as me) who will send the form, even in non-multiple selection cases, it has value to have another tag holding the actual value (and not only the input text). That would fix #40 and set good bases for #52.
What do you think?

Multiple selection

---

src/SimpleAutocomplete.svelte

This fixes a bug introduced with #54, that broke non-async highlighting, because `processListItems` was not called at the end of the `search` function.
This also fixes #64

Fixed non-async highlighting

---

README.md
src/App.svelte
src/LockedExample.svelte
src/SimpleAutocomplete.svelte

Fixed #52 
This adds two properties:
- lock: that locks the input when an item is selected
- readonly: that allows users to make the input field readonly

Lockable input

---

src/App.svelte
src/AsyncPreloadedExample.svelte
src/SimpleAutocomplete.svelte

Fixes #73
If selectedItem is given a value, and the component is async, then the item list will be loaded when the user will focus the input.

async: Loads item list on focus when the component is pre-initialized

---

src/SimpleAutocomplete.svelte

This minor change fixes situations where the string to highlight contains several spaces.

minor autocompletion regex fix

---

src/SimpleAutocomplete.svelte

Fixes #60 
If the user is using a search function to populate the list (e.g. using it to fetch results from remote server) then clear the items when the user provides an empty string.
This causes the search box to close as expected.

If using a search function clear items on empty search string

---

public/default.css
public/index.html
src/App.svelte

This patch adds a checkbox to the demo webpage to let users disable bulma style. This should help to debug style without bulma, and let the users see the default style of the component.

Add a checkbox in the demo page to disable bulma

---

src/SimpleAutocomplete.svelte
src/demo/AsyncGeneratorExample.svelte

This bugfix concerns async generators.
Previously, when an unsuccessful search B was done after a successful one A, the menu would display the A results until another successful search was done.

Fixed a situation when async generators returned no value

---

.github/workflows/test.yml
babel.config.js
jest.config.js
package-lock.json
package.json
src/SimpleAutocomplete.svelte
src/highlight.test.ts
tsconfig.json

This patch installs a testsuite with jest. Tests can be ran with `npm test`. It adds a github action so tests are ran for each commit and each pull request.
There is only one test for now, that tests the highlighting, but hopefully there will be more in the future!

unit tests and CI

---

src/demo/SimpleExample.svelte

Thank you for sharing this very useful component!
I noticed the first code example does not run due to a typo and an unused `highlightedItem`. This pull request should fix that.

Fix invalid example code 

---

src/SimpleAutocomplete.svelte

This fixes an issue with Chrome where it still autofills previous responses to this field.
The [Mozilla definition for the `autocomplete` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-autocomplete) allows two values: `on` or `off`.

Updated html5autocomplete to be "off" when falsy

---

src/SimpleAutocomplete.svelte

This one is a bit tricky: We had some trouble with the "autocomplete-input" styles and our css-framework. It is not so easy to reset those properly. So I created an option to disable the classes attached to the input.

New option: remove InputStyles

---

src/SimpleAutocomplete.svelte

I have the problem that my form hast a tab-hierarchy. There is no way to reach the field, without setting the tabindex.
So i added a new property.: tabindex.
the standard is set to "0", so there should no change to previous behavior:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

Add tabindex support to the input

---

package.json

Change the module structure to a more common structure and added "prepare" to scripts.
According to my ticket:
https://github.com/pstanoev/simple-svelte-autocomplete/issues/131

Module structure and github package

---

src/SimpleAutocomplete.svelte
src/async.test.ts
src/demo/AsyncExample.svelte

This patch fixes #154, adds tests to avoid regressions on the async side.
`prepareListItems` is not called anymore when a `searchFunction` is defined. This fixes filtering, and query highlighting.
@pstanoev could you review this and release a new version? :pray: :heart:

Fixed async behavior

---

README.md
src/SimpleAutocomplete.svelte
src/demo/CustomizationExample.svelte

I added two slots `dropdown-header` and `dropdown-footer` that are displayed before and after the item list.

Added dropdown header and footer slots

---

src/SimpleAutocomplete.svelte
src/demo/AsyncExample.svelte

Currently, when the input is focused, the behavior is different if a `searchFunction` is defined or not. When not defined, the menu always open, independently of `minCharactersToSearch`, when defined, the menu nevers opens, independently of `minCharactersToSearch`.
This patch does not change behavior when `searchFunction` is not defined, but when it is and `minCharactersToSearch` is 0, then the menu opens when the input is focused.
I am not sure this is what we want though, I think behavior probably should not be different wether `searchFunction` is defined or not.
What do you think?

Fixed minCharactersToSearch behavior with async

---

demo/MultipleExample.svelte
src/SimpleAutocomplete.svelte

`selectedItem` was evaluated to `true` even when it was `[]`, this would make the clear cross being displayed even when selection was empty when `multiple` was true.

Fixed multiple selection clear cross

---

src/SimpleAutocomplete.svelte
src/tests/multiple.test.ts
src/tests/sync.test.ts

This patch allows to use the `text` parameter to initialize the input value, wether the selection is unique or multiple.

Initialization with the 'text' parameter

---

src/SimpleAutocomplete.svelte

The latest svelte versions print warnings where displaying those warnings:
```
(!) Plugin svelte: A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
src/SimpleAutocomplete.svelte
1146:             <div class="tags has-addons">
1147:               <span class="tag">{safeLabelFunction(tagItem)}</span>
1148:               <span class="tag is-delete" on:click|preventDefault={unselectItem(tagItem)} />
^
1149:             </div>
1150:           </slot>
src/SimpleAutocomplete.svelte
1179:     />
1180:     {#if clearable}
1181:       <span on:click={clear} class="autocomplete-clear-button">{@html clearText}</span>
^
1182:     {/if}
1183:   </div>
src/SimpleAutocomplete.svelte
1192:       {#each filteredListItems as …
```

Fixed some accessibility warnings

---

src/SimpleAutocomplete.svelte

Without this patch, when `locked` is true, users can open the menu but cannot select items. This feels a very strange UX to me. Instead I suggest that the menu stays closed until users hit the clear button, and the menu would open automatically at this moment.
Alternatively, we could deselect the item when the input is clicked.

Keep menu closed when locked

---

src/SimpleAutocomplete.svelte

This is useful in cases one want to suggest items when the input is focused, before any input has been written. In such a case we want to call processListItems to sort the suggested items.

Call custom ordering functions when opening the menu with an empty input

---

demo/App.svelte

This PR addresses the issue of Flash of Unstyled Content (FOUC) that occurs when toggling between "Bulma" checkbox.

demo: fix style FOUC
